# Convenience Function
def uncommon_chord_map(chord):
    uncommon_chord_map = {
        'Fs11': 'Fs7',
        'Dminadd9': 'Dmin',
        'A7b9': 'A7',
        'Ab9': 'Ab7',
        'Cmaj7sus2': 'Cmaj7',
        'F7sus2': 'F7',
        'Gs13': 'Gs7',
        'Gminadd9': 'Gmin',
        'Fdimadd13': 'Bb7', # Fdim is functionally related to Bb7
        'Ebadd11': 'Eb',
        'Fs13': 'Fs7',
        'C11': 'C7',
        'Db13': 'Db7',
        'Fs7b9': 'Fs7',
        'F7b9': 'F7',
        'Fsaug': 'Fsaug',
        'A13b9': 'A7',
        'Cmaj911s': 'Cmaj7',
        'Gaugmaj7': 'Gaug',
        'Dsmin11': 'Dsmin7',
        'Dbadd11': 'Db',
        'Cminadd9': 'Cmin',
        'Asmaj7sus2': 'Asmaj7',
        'Gssus2': 'Gssus4', # sus2 is less common than sus4
        'Aaugmaj7': 'Aaug',
        'Abminadd13': 'Abmin',
        'Emaj13': 'Emaj7',
        'Fsmajs9': 'Fsmaj7', # Fsmaj9
        'Dsadd13': 'Ds',
        'Gbmin9': 'Gbmin7',
        'Fminmaj7': 'Fmin7',
        'Cminadd11': 'Cmin',
        'Emaj7sus2': 'Emaj7',
        'Db7sus4': 'Db7',
        'Gbdim': 'D7', # Gbdim (Fsdim) is functionally related to D7
        'Eaugmaj7': 'Eaug',
        'Dsadd11': 'Ds',
        'Ebmaj13': 'Ebmaj7',
        'Dsminadd13': 'Dsmin',
        'Gaugmaj9': 'Gaug',
        'Asadd9': 'As',
        'Gbdim7': 'D7', # Gbdim7 (Fsdim7) is functionally related to D7
        'Bmaj7sus2': 'Bmaj7',
        'Gsadd11': 'Gs',
        'Dsminadd9': 'Dsmin',
        'Ab11': 'Ab7',
        'Bb13b': 'Bb7',
        'Db11': 'Db7',
        'Abmin11': 'Abmin7',
        'Gsadd9': 'Gs',
        'Bb11': 'Bb7',
        'Cs7sus2': 'Cs7',
        'Bminadd9': 'Bmin',
        'C7b9': 'C7',
        'Eb7sus2': 'Eb7',
        'Fmaj911s': 'Fmaj7',
        'Cs11': 'Cs7',
        'Ebaug': 'Ebaug',
        'Fsminmaj7': 'Fsmin7',
        'Gsminadd11': 'Gsmin',
        'C7sus2': 'C7',
        'Bbadd11': 'Bb',
        'Bbaugmaj9': 'Bbaug',
        'Ebmajs9': 'Ebmaj7', # Ebmaj9
        'Fmajs911s': 'Fmaj7',
        'Gsadd13': 'Gs',
        'As7sus4': 'As7',
        'Dbmaj7sus2': 'Dbmaj7',
        'Bbmaj11': 'Bbmaj7',
        'Caugmaj7': 'Caug',
        'Eb13b9': 'Eb7',
        'Dsminmaj7': 'Dsmin7',
        'Faugmaj7': 'Faug',
        'Fsmaj911s': 'Fsmaj7',
        'Faugmaj9': 'Faug',
        'Dbaugmaj7': 'Dbaug',
        'Ab7b9': 'Ab7',
        'As9': 'As7',
        'C13b9': 'C7',
        'Eminadd11': 'Emin',
        'Gbaug': 'Gbaug',
        'Dbdim7': 'A7', # Dbdim7 (Csdim7) is functionally related to A7
        'Dsmaj9': 'Dsmaj7',
        'Dsmaj7sus2': 'Dsmaj7',
        'Fminadd9': 'Fmin',
        'Fsaugmaj9': 'Fsaug',
        'Gb13': 'Gb7',
        'Abaug': 'Abaug',
        'Gbsus4': 'Gb',
        'Gsminmaj7': 'Gsmin7',
        'Gminadd11': 'Gmin',
        'Fsmaj7sus2': 'Fsmaj7',
        'Ds11': 'Ds7',
        'Eaugmaj9': 'Eaug',
        'Emin13': 'Emin7',
        'Fsminb9': 'Fsmin7',
        'Dmaj13': 'Dmaj7',
        'Bbmajs911s': 'Bbmaj7',
        'Fs13b': 'Fs7',
        'Fsminmaj9': 'Fsmin7',
        'Dmin13': 'Dmin7',
        'Asaug': 'Asaug',
        'Abaugmaj7': 'Abaug',
        'Bmajs9': 'Bmaj7', # Bmaj9
        'Bmaj911s': 'Bmaj7',
        'Csmajs9': 'Csmaj7', # Csmaj9
        'Amaj7sus4': 'Amaj7',
        'Amin13': 'Amin7',
        'Gs11': 'Gs7',
        'Gb13b9': 'Gb7',
        'G13b': 'G7',
        'Dsaugmaj7': 'Dsaug',
        'Abadd11': 'Ab',
        'Dmajs911s': 'Dmaj7',
        'Csminmaj7': 'Csmin7',
        'Cmajs9': 'Cmaj7', # Cmaj9
        'Bbaugmaj7': 'Bbaug',
        'Bbmaj911s': 'Bbmaj7',
        'Ebmaj1311s': 'Ebmaj7',
        'Eb11': 'Eb7',
        'Bmaj13': 'Bmaj7',
        'Fmin11': 'Fmin7',
        'As13': 'As7',
        'Bb7b9': 'Bb7',
        'Dbmaj13': 'Dbmaj7',
        'Dbmin9': 'Dbmin7',
        'G11b9': 'G7',
        'Gs13b': 'Gs7',
        'Dbaug': 'Dbaug',
        'Dsmajs9': 'Dsmaj7', # Dsmaj9
        'Csmaj7sus2': 'Csmaj7',
        'B11s': 'B7',
        'F11s': 'F7',
        'Fminadd11': 'Fmin',
        'Ebminadd11': 'Ebmin',
        'Daugmaj7': 'Daug',
        'Gmajs9': 'Gmaj7', # Gmaj9
        'Db7sus2': 'Db7',
        'Fsmaj9': 'Fsmaj7',
        'A13b': 'A7',
        'E13b': 'E7',
        'Amaj13': 'Amaj7',
        'Cs7b9': 'Cs7',
        'Asminadd9': 'Asmin',
        'Ds7sus4': 'Ds7',
        'Ebmaj911s': 'Ebmaj7',
        'Bbmin13': 'Bbmin7',
        'Abmaj13': 'Abmaj7',
        'Fsmaj7sus4': 'Fsmaj7',
        'Dsmaj11': 'Dsmaj7',
        'Aaugmaj9': 'Aaug',
        'Asmin11': 'Asmin7',
        'Abaugmaj9': 'Abaug',
        'Abmaj7sus2': 'Abmaj7',
        'Gmaj7sus4': 'Gmaj7',
        'Gbadd11': 'Gb',
        'Gsdim9': 'E7', # Gsdim9 is functionally related to E7
        'Ebaugmaj7': 'Ebaug',
        'Gsaugmaj7': 'Gsaug',
        'Bmaj11': 'Bmaj7',
        'Asmajs9': 'Asmaj7', # Asmaj9
        'Bbmaj13': 'Bbmaj7',
        'Csminadd9': 'Csmin',
        'Dminadd11': 'Dmin',
        'Dbminmaj7': 'Dbmin7',
        'Gb7sus4': 'Gb7',
        'Cmajs911s': 'Cmaj7',
        'Bb7sus2': 'Bb7',
        'Bmaj7sus4': 'Bmaj7',
    }
    try:
        return uncommon_chord_map[chord]
    except KeyError:
        return chord

def notes_map(chord):

    notes_to_midi = {
        'C': 60, 'C#': 61, 'Db': 61,
        'D': 62, 'D#': 63, 'Eb': 63,
        'E': 64, 'Fb': 64, 'E#': 65,
        'F': 65, 'F#': 66, 'Gb': 66,
        'G': 67, 'G#': 68, 'Ab': 68,
        'A': 69, 'A#': 70, 'Bb': 70,
        'B': 71, 'Cb': 71, 'B#': 72,
        'Ebb': 63, 'Gbb': 66, 'Bbb': 69, 'Abb': 67, 'Cbb': 59, 'Dbb': 61, 'Fbb': 64,
        'F##': 67, 'G##': 69, 'A##': 71, 'C##': 62, 'D##': 64
    }

    notes_map = {
        "Eadd13": ["E", "G#", "B", "C#"],
        "Ab13": ["Ab", "C", "Eb", "Gb", "Bb", "F"],
        "Gbno3d": ["Gb", "Db"],
        "Csminadd13": ["C#", "E", "G#", "A#"],
        "Cdim7": ["C", "Eb", "Gb", "A"],
        "Gb": ["Gb", "Bb", "Db"],
        "Emaj9": ["E", "G#", "B", "D#", "F#"],
        "Csmin": ["C#", "E", "G#"],
        "Dsus4": ["D", "G", "A"],
        "Bminadd13": ["B", "D", "F#", "G#"],
        "Gmin": ["G", "Bb", "D"],
        "Gbmin7": ["Gb", "A", "Db", "E"],
        "Csus2": ["C#", "D#", "G#"],
        "B7": ["B", "D#", "F#", "A"],
        "F": ["F", "A", "C"],
        "Fsmin": ["F#", "A", "C#"],
        "Bbsus4": ["Bb", "Eb", "F"],
        "Emin7": ["E", "G", "B", "D"],
        "Dmaj7sus4": ["D", "G", "A", "C#"],
        "Gs": ["G#", "B#", "D#"],
        "Dbadd9": ["Db", "F", "Ab", "Eb"],
        "Ebmin9": ["Eb", "Gb", "Bb", "Db", "F"],
        "Fdim": ["F", "Ab", "B"],
        "Adim7": ["A", "C", "Eb", "Gb"],
        "Gbmaj7": ["Gb", "Bb", "Db", "F"],
        "Gadd9": ["G", "B", "D", "A"],
        "Bdim7": ["B", "D", "F", "Ab"],
        "Bmaj9": ["B", "D#", "F#", "A#", "C#"],
        "Gbadd13": ["Gb", "Bb", "Db", "Eb"],
        "Ds7": ["D#", "G", "A#", "C#"],
        "Asadd13": ["A#", "D", "F", "G"],
        "Gb7": ["Gb", "Bb", "Db", "Fb"],
        "Cs7sus4": ["C#", "F#", "G#", "B"],
        "Gsmin7": ["G#", "B", "D#", "F#"],
        "Bbno3d": ["Bb", "F"],
        "Gsus4": ["G", "C", "D"],
        "D7": ["D", "F#", "A", "C"],
        "Csadd13": ["C#", "F", "G#", "A#"],
        "Eminmaj7": ["E", "G", "B", "D#"],
        "Fsmin9": ["F#", "A", "C#", "E", "G#"],
        "Cno3d": ["C", "G"],
        "Cmaj9": ["C", "E", "G", "B", "D"],
        "Ds9": ["D#", "G", "A#", "C#", "F"],
        "Bmin": ["B", "D", "F#"],
        "Fsadd9": ["F#", "A#", "C#", "G#"],
        "F7": ["F", "A", "C", "Eb"],
        "Fsminadd11": ["F#", "A", "C#", "B"],
        "Dsus2": ["D", "E", "A"],
        "Bminmaj7": ["B", "D", "F#", "A#"],
        "Eadd11": ["E", "G#", "B", "A"],
        "Badd11": ["B", "D#", "F#", "E"],
        "Dbaug": ["Db", "F", "A"],
        "Dminmaj7": ["D", "F", "A", "C#"],
        "G9": ["G", "B", "D", "F", "A"],
        "Cmaj7": ["C", "E", "G", "B"],
        "Gmin11": ["G", "Bb", "D", "F", "A", "C"],
        "Ebmaj7": ["Eb", "G", "Bb", "D"],
        "Dbmaj7": ["Db", "F", "Ab", "C"],
        "G7sus4": ["G", "C", "D", "F"],
        "A7sus2": ["A", "B", "E", "G"],
        "Dmaj9": ["D", "F#", "A", "C#", "E"],
        "Badd9": ["B", "D#", "F#", "C#"],
        "Gmaj9": ["G", "B", "D", "F#", "A"],
        "Fsmin13": ["F#", "A", "C#", "E", "G#", "D#"],
        "Assus2": ["A#", "B#", "E#"],
        "Cssus2": ["C#", "D#", "G#"],
        "Bbmin": ["Bb", "Db", "F"],
        "Fmin7": ["F", "Ab", "C", "Eb"],
        "Fmaj9": ["F", "A", "C", "E", "G"],
        "Asus2": ["A", "B", "E"],
        "Asdim7": ["A#", "C#", "E", "G"],
        "Ddim": ["D", "F", "Ab"],
        "Bmin9": ["B", "D", "F#", "A", "C#"],
        "F9": ["F", "A", "C", "Eb", "G"],
        "Dssus4": ["D#", "G#", "A#"],
        "Bmaj7": ["B", "D#", "F#", "A#"],
        "Ano3d": ["A", "E"],
        "Gsmin9": ["G#", "B", "D#", "F#", "A#"],
        "Dsmaj7": ["D#", "G", "A#", "D"],
        "Asno3d": ["A#", "F"],
        "Bbsus2": ["Bb", "C", "F"],
        "Fsminadd13": ["F#", "A", "C#", "D#"],
        "Gadd13": ["G", "B", "D", "E"],
        "Cmin7": ["C", "Eb", "G", "Bb"],
        "Gbaug": ["Gb", "Bb", "D"],
        "Fsaugmaj7": ["F#", "A#", "D", "F"],
        "Aminadd13": ["A", "C", "E", "F#"],
        "Bbmaj7": ["Bb", "D", "F", "A"],
        "Dbadd13": ["Db", "F", "Ab", "Bb"],
        "Fsmin11": ["F#", "A", "C#", "E", "G#", "B"],
        "Fdim7": ["F", "Ab", "B", "D"],
        "Fmaj7": ["F", "A", "C", "E"],
        "Fmaj13": ["F", "A", "C", "E", "G", "D"],
        "D11": ["D", "F#", "A", "C", "E", "G"],
        "Bbadd9": ["Bb", "D", "F", "C"],
        "Bbmaj9": ["Bb", "D", "F", "A", "C"],
        "Cmin9": ["C", "Eb", "G", "Bb", "D"],
        "Dbmin7": ["Db", "Fb", "Ab", "Cb"],
        "Fssus4": ["F#", "B", "C#"],
        "Emin9": ["E", "G", "B", "D", "F#"],
        "Ebaug": ["Eb", "G", "B"],
        "Ab": ["Ab", "C", "Eb"],
        "Abno3d": ["Ab", "Eb"],
        "B7sus4": ["B", "E", "F#", "A"],
        "Gsdim7": ["G#", "B", "D", "F"],
        "E7": ["E", "G#", "B", "D"],
        "Db9": ["Db", "F", "Ab", "Cb", "Eb"],
        "Fminadd13": ["F", "Ab", "C", "D"],
        "Ebmin11": ["Eb", "Gb", "Bb", "Db", "F", "Ab"],
        "Adim": ["A", "C", "Eb"],
        "Fadd13": ["F", "A", "C", "D"],
        "Baug": ["B", "D#", "G"],
        "Assus4": ["A#", "D#", "E#"],
        "Fs7sus2": ["F#", "G#", "C#", "E"],
        "Bbdim7": ["Bb", "Db", "Fb", "G"],
        "Cadd9": ["C", "E", "G", "D"],
        "Dsdim": ["D#", "F#", "A"],
        "Gmaj13": ["G", "B", "D", "F#", "A", "E"],
        "G7b9": ["G", "B", "D", "F", "Ab"],
        "Gmaj7sus2": ["G", "A", "D", "F#"],
        "Cminmaj7": ["C", "Eb", "G", "B"],
        "E9": ["E", "G#", "B", "D", "F#"],
        "Cmin": ["C", "Eb", "G"],
        "Csmin7": ["C#", "E", "G#", "B"],
        "Abdim7": ["Ab", "Cb", "Ebb", "Gbb"],
        "Csus4": ["C", "F", "G"],
        "Dno3d": ["D", "A"],
        "Bbdim": ["Bb", "Db", "Fb"],
        "Bmin11": ["B", "D", "F#", "A", "C#", "E"],
        "G13": ["G", "B", "D", "F", "A", "E"],
        "Emaj7": ["E", "G#", "B", "D#"],
        "Eb13": ["Eb", "G", "Bb", "Db", "F", "C"],
        "Dmin11": ["D", "F", "A", "C", "E", "G"],
        "Amin": ["A", "C", "E"],
        "Cminadd13": ["C", "Eb", "G", "A"],
        "Asmin7": ["A#", "C#", "E#", "G#"],
        "Gsno3d": ["G#", "D#"],
        "Eaug": ["E", "G#", "C"],
        "Ebmin7": ["Eb", "Gb", "Bb", "Db"],
        "Csadd11": ["C#", "F", "G#", "F#"],
        "Faug": ["F", "A", "C#"],
        "Gmin7": ["G", "Bb", "D", "F"],
        "Fs": ["F#", "A#", "C#"],
        "Emin11": ["E", "G", "B", "D", "F#", "A"],
        "Csdim7": ["C#", "E", "G", "Bb"],
        "A7": ["A", "C#", "E", "G"],
        "Dbno3d": ["Db", "Ab"],
        "Ebadd13": ["Eb", "G", "Bb", "C"],
        "Amin7": ["A", "C", "E", "G"],
        "Eb7sus4": ["Eb", "Ab", "Bb", "Db"],
        "Gmin9": ["G", "Bb", "D", "F", "A"],
        "Gbadd9": ["Gb", "Bb", "Db", "Ab"],
        "D": ["D", "F#", "A"],
        "Ebdim7": ["Eb", "Gb", "A", "C"],
        "Eb": ["Eb", "G", "Bb"],
        "Dsmin": ["D#", "F#", "A#"],
        "Dssus2": ["D#", "E#", "A#"],
        "Csmaj7": ["C#", "E#", "G#", "B#"],
        "Fsus4": ["F", "Bb", "C"],
        "Absus2": ["Ab", "Bb", "Eb"],
        "Fsaug": ["F#", "A#", "D"],
        "Cs7": ["C#", "E#", "G#", "B"],
        "Csdim": ["C#", "E", "G"],
        "Eminadd9": ["E", "G", "B", "F#"],
        "A": ["A", "C#", "E"],
        "Dsno3d": ["D#", "A#"],
        "Bb7sus4": ["Bb", "Eb", "F", "Ab"],
        "G11": ["G", "B", "D", "F", "A", "C"],
        "Fmaj7sus2": ["F", "G", "C", "E"],
        "C9": ["C", "E", "G", "Bb", "D"],
        "Eadd9": ["E", "G#", "B", "F#"],
        "D7sus4": ["D", "G", "A", "C"],
        "A7sus4": ["A", "D", "E", "G"],
        "Gadd11": ["G", "B", "D", "C"],
        "Gbminadd13": ["Gb", "A", "Db", "Eb"],
        "Fs7sus4": ["F#", "B", "C#", "E"],
        "Bbaug": ["Bb", "D", "F#"],
        "Ebdim": ["Eb", "Gb", "Bbb"],
        "E7b9": ["E", "G#", "B", "D", "F"],
        "D7sus2": ["D", "E", "A", "C"],
        "Amin11": ["A", "C", "E", "G", "B", "D"],
        "Dadd11": ["D", "F#", "A", "G"],
        "Gs7sus4": ["G#", "C#", "D#", "F#"],
        "Ebminadd13": ["Eb", "Gb", "Bb", "C"],
        "Csaug": ["C#", "E#", "G##"],
        "Gminmaj7": ["G", "Bb", "D", "F#"],
        "Gs7": ["G#", "B#", "D#", "F#"],
        "Fsadd11": ["F#", "A#", "C#", "B"],
        "Edim": ["E", "G", "Bb"],
        "Gsus2": ["G", "A", "D"],
        "D9": ["D", "F#", "A", "C", "E"],
        "B13b": ["B", "D#", "F#", "A", "G"],
        "A13": ["A", "C#", "E", "G", "B", "F#"],
        "Bdim": ["B", "D", "F"],
        "Amaj7sus2": ["A", "B", "E", "G#"],
        "C7": ["C", "E", "G", "Bb"],
        "Abdim": ["Ab", "Cb", "Ebb"],
        "Bno3d": ["B", "F#"],
        "Asmin": ["A#", "C#", "E#"],
        "Asaug": ["A#", "D", "F#"],
        "C": ["C", "E", "G"],
        "Dbmin": ["Db", "Fb", "Ab"],
        "Dbminadd13": ["Db", "Fb", "Ab", "Bb"],
        "Aminadd11": ["A", "C", "E", "D"],
        "Gdim": ["G", "Bb", "Db"],
        "Dminadd13": ["D", "F", "A", "B"],
        "E": ["E", "G#", "B"],
        "Ddim7": ["D", "F", "Ab", "Cb"],
        "Ebsus4": ["Eb", "Ab", "Bb"],
        "D7b9": ["D", "F#", "A", "C", "Eb"],
        "Gno3d": ["G", "D"],
        "Gbmaj9": ["Gb", "Bb", "Db", "F", "Ab"],
        "Bbminadd13": ["Bb", "Db", "F", "G"],
        "Fno3d": ["F", "C"],
        "Csaugmaj7": ["C#", "E#", "G##", "B#"],
        "Fsminadd9": ["F#", "A", "C#", "G#"],
        "Dmaj7": ["D", "F#", "A", "C#"],
        "Abadd13": ["Ab", "C", "Eb", "F"],
        "Fmin9": ["F", "Ab", "C", "Eb", "G"],
        "Fssus2": ["F#", "G#", "C#"],
        "Eno3d": ["E", "B"],
        "Dmin9": ["D", "F", "A", "C", "E"],
        "Csmin9": ["C#", "E", "G#", "B", "D#"],
        "Edim7": ["E", "G", "Bb", "Db"],
        "Dmin": ["D", "F", "A"],
        "G": ["G", "B", "D"],
        "B7sus2": ["B", "C#", "F#", "A"],
        "Gb9": ["Gb", "Bb", "Db", "Fb", "Ab"],
        "Gsmin11": ["G#", "B", "D#", "F#", "A#", "C#"],
        "Cmaj13": ["C", "E", "G", "B", "D", "A"],
        "Ebmin": ["Eb", "Gb", "Bb"],
        "Caug": ["C", "E", "G#"],
        "B7b9": ["B", "D#", "F#", "A", "C"],
        "Cmin11": ["C", "Eb", "G", "Bb", "D", "F"],
        "B11": ["B", "D#", "F#", "A", "C#", "E"],
        "Eb7": ["Eb", "G", "Bb", "Db"],
        "Gsmaj7": ["G#", "B#", "D#", "G"],
        "F13": ["F", "A", "C", "Eb", "G", "D"],
        "Csmin11": ["C#", "E", "G#", "B", "D#", "F#"],
        "Dbsus2": ["Db", "Eb", "Ab"],
        "Asus4": ["A", "D", "E"],
        "Gsdim": ["G#", "B", "D"],
        "C13": ["C", "E", "G", "Bb", "D", "A"],
        "Eb9": ["Eb", "G", "Bb", "Db", "F"],
        "Fsno3d": ["F#", "C#"],
        "Asmaj7": ["A#", "D", "E#", "G##"],
        "D13": ["D", "F#", "A", "C", "E", "B"],
        "Aadd9": ["A", "C#", "E", "B"],
        "Dsadd9": ["D#", "G", "A#", "E#"],
        "Abmaj7": ["Ab", "C", "Eb", "G"],
        "Ebmaj9": ["Eb", "G", "Bb", "D", "F"],
        "A9": ["A", "C#", "E", "G", "B"],
        "Gsaug": ["G#", "B#", "E"],
        "Abaug": ["Ab", "C", "E"],
        "Abadd9": ["Ab", "C", "Eb", "Bb"],
        "Gsminadd13": ["G#", "B", "D#", "E#"],
        "Cadd13": ["C", "E", "G", "A"],
        "C7sus4": ["C", "F", "G", "Bb"],
        "Fmin": ["F", "Ab", "C"],
        "Bb": ["Bb", "D", "F"],
        "Absus4": ["Ab", "Db", "Eb"],
        "Emin": ["E", "G", "B"],
        "Aadd13": ["A", "C#", "E", "F#"],
        "Gsmin": ["G#", "B", "D#"],
        "Bsus2": ["B", "C#", "F#"],
        "Dbsus4": ["Db", "Gb", "Ab"],
        "Asdim": ["A#", "C#", "E"],
        "B9": ["B", "D#", "F#", "A", "C#"],
        "Bmin7": ["B", "D", "F#", "A"],
        "Esus2": ["E", "F#", "B"],
        "Fsdim": ["F#", "A", "C"],
        "Badd13": ["B", "D#", "F#", "G#"],
        "Fsmin7": ["F#", "A", "C#", "E"],
        "G7sus2": ["G", "A", "D", "F"],
        "Bb9": ["Bb", "D", "F", "Ab", "C"],
        "E11": ["E", "G#", "B", "D", "F#", "A"],
        "Ab7sus4": ["Ab", "Db", "Eb", "Gb"],
        "Fs7": ["F#", "A#", "C#", "E"],
        "Bbmin7": ["Bb", "Db", "F", "Ab"],
        "Cdim": ["C", "Eb", "Gb"],
        "Dadd9": ["D", "F#", "A", "E"],
        "Aminadd9": ["A", "C", "E", "B"],
        "Fs9": ["F#", "A#", "C#", "E", "G#"],
        "Abmaj9": ["Ab", "C", "Eb", "G", "Bb"],
        "Bsus4": ["B", "E", "F#"],
        "Abmin7": ["Ab", "Cb", "Eb", "Gb"],
        "Gbmin": ["Gb", "A", "Db"],
        "Dadd13": ["D", "F#", "A", "B"],
        "Csno3d": ["C#", "G#"],
        "Bb13": ["Bb", "D", "F", "Ab", "C", "G"],
        "Bbadd13": ["Bb", "D", "F", "G"],
        "Ebadd9": ["Eb", "G", "Bb", "F"],
        "Fadd9": ["F", "A", "C", "G"],
        "Dmaj7sus2": ["D", "E", "A", "C#"],
        "Amin9": ["A", "C", "E", "G", "B"],
        "F11": ["F", "A", "C", "Eb", "G", "Bb"],
        "Ebno3d": ["Eb", "Bb"],
        "F7sus4": ["F", "Bb", "C", "Eb"],
        "Csmaj9": ["C#", "E#", "G#", "B#", "D#"],
        "B13": ["B", "D#", "F#", "A", "C#", "G#"],
        "Amaj7": ["A", "C#", "E", "G#"],
        "E7sus4": ["E", "A", "B", "D"],
        "Dsdim7": ["D#", "F#", "A", "C"],
        "Bbmin9": ["Bb", "Db", "F", "Ab", "C"],
        "Fsus2": ["F", "G", "C"],
        "E13": ["E", "G#", "B", "D", "F#", "C#"],
        "Baugmaj7": ["B", "D#", "G", "A#"],
        "Aaug": ["A", "C#", "E#"],
        "Gssus4": ["G#", "C#", "D#"],
        "Cs9": ["C#", "E#", "G#", "B", "D#"],
        "Gmaj7": ["G", "B", "D", "F#"],
        "Gdim7": ["G", "Bb", "Db", "E"],
        "A11": ["A", "C#", "E", "G", "B", "D"],
        "Asminadd13": ["A#", "C#", "E#", "F##"],
        "Abmin9": ["Ab", "Cb", "Eb", "Gb", "Bb"],
        "E7sus2": ["E", "F#", "B", "D"],
        "Cadd11": ["C", "E", "G", "F"],
        "Abmin": ["Ab", "Cb", "Eb"],
        "Amaj9": ["A", "C#", "E", "G#", "B"],
        "Dmin7": ["D", "F", "A", "C"],
        "Aminmaj7": ["A", "C", "E", "G#"],
        "Dmajs9": ["D", "F#", "A", "C#", "E#"],
        "Fadd11": ["F", "A", "C", "Bb"],
        "Bminadd11": ["B", "D", "F#", "E"],
        "Dbmaj9": ["Db", "F", "Ab", "C", "Eb"],
        "Dbdim": ["Db", "Fb", "Abb"],
        "As7": ["A#", "D", "F", "G#"],
        "Emajs9": ["E", "G#", "B", "D#", "F##"],
        "Db7": ["Db", "F", "Ab", "Cb"],
        "Dsaug": ["D#", "G", "B"],
        "Aadd11": ["A", "C#", "E", "D"],
        "Bbminmaj7": ["Bb", "Db", "F", "A"],
        "Gaug": ["G", "B", "D#"],
        "Ab7": ["Ab", "C", "Eb", "Gb"],
        "Bb7": ["Bb", "D", "F", "Ab"],
        "Gmaj911s": ["G", "B", "D", "F#", "A", "C#"],
        "Gs9": ["G#", "B#", "D#", "F#", "A#"],
        "Daug": ["D", "F#", "A#"],
        "Gmin13": ["G", "Bb", "D", "F", "A", "E"],
        "G7": ["G", "B", "D", "F"],
        "Fsmaj7": ["F#", "A#", "C#", "E#"],
        "Eminadd13": ["E", "G", "B", "C#"],
        "Cssus4": ["C#", "F#", "G#"],
        "Dsmin7": ["D#", "F#", "A#", "C#"],
        "Ebsus2": ["Eb", "F", "Bb"],
        "Fsadd13": ["F#", "A#", "C#", "D#"],
        "Gminadd13": ["G", "Bb", "D", "E"],
        "Fsdim7": ["F#", "A", "C", "Eb"],
        "Dsmin9": ["D#", "F#", "A#", "C#", "E#"],
        "Csadd9": ["C#", "E#", "G#", "D#"],
        "Esus4": ["E", "A", "B"]
    }
    try:
        midi = []
        for i, note in enumerate(notes_map[chord]):
            if i>2:
                midi.append(notes_to_midi[note] + 12)
            else:
                midi.append(notes_to_midi[note])
        return midi
    except KeyError:
        return None