# Convenience Function
def uncommon_chord_map(chord):
    uncommon_chord_map = {
        'Fs11': 'Fs7',
        'Dminadd9': 'Dmin',
        'A7b9': 'A7',
        'Ab9': 'Ab7',
        'Cmaj7sus2': 'Cmaj7',
        'F7sus2': 'F7',
        'Gs13': 'Gs7',
        'Gminadd9': 'Gmin',
        'Fdimadd13': 'Bb7', # Fdim is functionally related to Bb7
        'Ebadd11': 'Eb',
        'Fs13': 'Fs7',
        'C11': 'C7',
        'Db13': 'Db7',
        'Fs7b9': 'Fs7',
        'F7b9': 'F7',
        'Fsaug': 'Fsaug',
        'A13b9': 'A7',
        'Cmaj911s': 'Cmaj7',
        'Gaugmaj7': 'Gaug',
        'Dsmin11': 'Dsmin7',
        'Dbadd11': 'Db',
        'Cminadd9': 'Cmin',
        'Asmaj7sus2': 'Asmaj7',
        'Gssus2': 'Gssus4', # sus2 is less common than sus4
        'Aaugmaj7': 'Aaug',
        'Abminadd13': 'Abmin',
        'Emaj13': 'Emaj7',
        'Fsmajs9': 'Fsmaj7', # Fsmaj9
        'Dsadd13': 'Ds',
        'Gbmin9': 'Gbmin7',
        'Fminmaj7': 'Fmin7',
        'Cminadd11': 'Cmin',
        'Emaj7sus2': 'Emaj7',
        'Db7sus4': 'Db7',
        'Gbdim': 'D7', # Gbdim (Fsdim) is functionally related to D7
        'Eaugmaj7': 'Eaug',
        'Dsadd11': 'Ds',
        'Ebmaj13': 'Ebmaj7',
        'Dsminadd13': 'Dsmin',
        'Gaugmaj9': 'Gaug',
        'Asadd9': 'As',
        'Gbdim7': 'D7', # Gbdim7 (Fsdim7) is functionally related to D7
        'Bmaj7sus2': 'Bmaj7',
        'Gsadd11': 'Gs',
        'Dsminadd9': 'Dsmin',
        'Ab11': 'Ab7',
        'Bb13b': 'Bb7',
        'Db11': 'Db7',
        'Abmin11': 'Abmin7',
        'Gsadd9': 'Gs',
        'Bb11': 'Bb7',
        'Cs7sus2': 'Cs7',
        'Bminadd9': 'Bmin',
        'C7b9': 'C7',
        'Eb7sus2': 'Eb7',
        'Fmaj911s': 'Fmaj7',
        'Cs11': 'Cs7',
        'Ebaug': 'Ebaug',
        'Fsminmaj7': 'Fsmin7',
        'Gsminadd11': 'Gsmin',
        'C7sus2': 'C7',
        'Bbadd11': 'Bb',
        'Bbaugmaj9': 'Bbaug',
        'Ebmajs9': 'Ebmaj7', # Ebmaj9
        'Fmajs911s': 'Fmaj7',
        'Gsadd13': 'Gs',
        'As7sus4': 'As7',
        'Dbmaj7sus2': 'Dbmaj7',
        'Bbmaj11': 'Bbmaj7',
        'Caugmaj7': 'Caug',
        'Eb13b9': 'Eb7',
        'Dsminmaj7': 'Dsmin7',
        'Faugmaj7': 'Faug',
        'Fsmaj911s': 'Fsmaj7',
        'Faugmaj9': 'Faug',
        'Dbaugmaj7': 'Dbaug',
        'Ab7b9': 'Ab7',
        'As9': 'As7',
        'C13b9': 'C7',
        'Eminadd11': 'Emin',
        'Gbaug': 'Gbaug',
        'Dbdim7': 'A7', # Dbdim7 (Csdim7) is functionally related to A7
        'Dsmaj9': 'Dsmaj7',
        'Dsmaj7sus2': 'Dsmaj7',
        'Fminadd9': 'Fmin',
        'Fsaugmaj9': 'Fsaug',
        'Gb13': 'Gb7',
        'Abaug': 'Abaug',
        'Gbsus4': 'Gb',
        'Gsminmaj7': 'Gsmin7',
        'Gminadd11': 'Gmin',
        'Fsmaj7sus2': 'Fsmaj7',
        'Ds11': 'Ds7',
        'Eaugmaj9': 'Eaug',
        'Emin13': 'Emin7',
        'Fsminb9': 'Fsmin7',
        'Dmaj13': 'Dmaj7',
        'Bbmajs911s': 'Bbmaj7',
        'Fs13b': 'Fs7',
        'Fsminmaj9': 'Fsmin7',
        'Dmin13': 'Dmin7',
        'Asaug': 'Asaug',
        'Abaugmaj7': 'Abaug',
        'Bmajs9': 'Bmaj7', # Bmaj9
        'Bmaj911s': 'Bmaj7',
        'Csmajs9': 'Csmaj7', # Csmaj9
        'Amaj7sus4': 'Amaj7',
        'Amin13': 'Amin7',
        'Gs11': 'Gs7',
        'Gb13b9': 'Gb7',
        'G13b': 'G7',
        'Dsaugmaj7': 'Dsaug',
        'Abadd11': 'Ab',
        'Dmajs911s': 'Dmaj7',
        'Csminmaj7': 'Csmin7',
        'Cmajs9': 'Cmaj7', # Cmaj9
        'Bbaugmaj7': 'Bbaug',
        'Bbmaj911s': 'Bbmaj7',
        'Ebmaj1311s': 'Ebmaj7',
        'Eb11': 'Eb7',
        'Bmaj13': 'Bmaj7',
        'Fmin11': 'Fmin7',
        'As13': 'As7',
        'Bb7b9': 'Bb7',
        'Dbmaj13': 'Dbmaj7',
        'Dbmin9': 'Dbmin7',
        'G11b9': 'G7',
        'Gs13b': 'Gs7',
        'Dbaug': 'Dbaug',
        'Dsmajs9': 'Dsmaj7', # Dsmaj9
        'Csmaj7sus2': 'Csmaj7',
        'B11s': 'B7',
        'F11s': 'F7',
        'Fminadd11': 'Fmin',
        'Ebminadd11': 'Ebmin',
        'Daugmaj7': 'Daug',
        'Gmajs9': 'Gmaj7', # Gmaj9
        'Db7sus2': 'Db7',
        'Fsmaj9': 'Fsmaj7',
        'A13b': 'A7',
        'E13b': 'E7',
        'Amaj13': 'Amaj7',
        'Cs7b9': 'Cs7',
        'Asminadd9': 'Asmin',
        'Ds7sus4': 'Ds7',
        'Ebmaj911s': 'Ebmaj7',
        'Bbmin13': 'Bbmin7',
        'Abmaj13': 'Abmaj7',
        'Fsmaj7sus4': 'Fsmaj7',
        'Dsmaj11': 'Dsmaj7',
        'Aaugmaj9': 'Aaug',
        'Asmin11': 'Asmin7',
        'Abaugmaj9': 'Abaug',
        'Abmaj7sus2': 'Abmaj7',
        'Gmaj7sus4': 'Gmaj7',
        'Gbadd11': 'Gb',
        'Gsdim9': 'E7', # Gsdim9 is functionally related to E7
        'Ebaugmaj7': 'Ebaug',
        'Gsaugmaj7': 'Gsaug',
        'Bmaj11': 'Bmaj7',
        'Asmajs9': 'Asmaj7', # Asmaj9
        'Bbmaj13': 'Bbmaj7',
        'Csminadd9': 'Csmin',
        'Dminadd11': 'Dmin',
        'Dbminmaj7': 'Dbmin7',
        'Gb7sus4': 'Gb7',
        'Cmajs911s': 'Cmaj7',
        'Bb7sus2': 'Bb7',
        'Bmaj7sus4': 'Bmaj7',
    }
    try:
        return uncommon_chord_map[chord]
    except KeyError:
        return chord